---
title:
  "Binomial Regression"
author: "Alex Berk"
output: 
  html_document:
        toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```

```{r, include=FALSE}

library(tidyverse)
library(lubridate)
library(mgcv)
library(marginaleffects)
library(MuMIn)
library(car)
library(corrplot)
library(stats)
library(tseries)
library(DHARMa)

conflicted::conflict_prefer("select","dplyr")
```

# Prepare data

```{r}

options(na.action = "na.exclude")

# variables to include:
c = c( "Chlorophyll", "Regions", "Date","Year", "Month",  "season","SAC","lagSAC", 
       "EXPORT","OUT","lagOUT", "SJR", "lagSJR", "Index","lagIndex","DissAmmonia",
       "lagDissAmmonia", "TotPhos","lagTotPhos","DissNitrateNitrite", 
       "lagDissNitrateNitrite","Temperature","lagTemperature","Secchi",
       "lagSecchi","Conductivity",  "lagConductivity","season_num", 
       "DissOrthophos", "lagDissOrthophos", "clam_step")


df <- read.csv("Data/regional_integrated_dataset3.csv" )

df$Date = as.Date(df$Date)

# 1979 is the start of the study period.
df <- subset(df,df$Date >= "1979-01-01")

# Changing categorical variables to factors
df$Regions = as.factor(df$Regions)
df$season = as.factor(df$season)
df$season_num = as.numeric(df$season)


#Replacing clam variables with a step function (pre/post potamocorbula introduction to the Bay in 1987)
df <- df%>%mutate(clam_step=if_else(Year>1987, "post clam", "pre clam")) 
df$clam_step <- as.factor(df$clam_step)

df <- subset(df, select = c) 

#Binary transformation of bloom absence/presence
bloom_thresholds <- df %>%
  group_by(Regions) %>%
  summarise(mean = mean(Chlorophyll,na.rm=T),sd=sd(Chlorophyll,na.rm=T)) %>%
  mutate(bloom_thr = mean + sd) %>%
  select(-mean,-sd)

#mean/d group by region
#HABs vs BABs coming from different dataset
  
df <- df %>%
  merge(bloom_thresholds,by="Regions",all.x=T) %>%
  mutate(bloom = case_when(Chlorophyll > bloom_thr ~ 1,
                           .default = 0))

paste0("Number of blooms = ", sum(df$bloom))

# z-score standardizing the dataset for more logical comparison of predictors. This facilitates comparison of effect sizes between variables.
df <- df %>% mutate(across(!c(bloom,Regions,season,Date,Month, Year, season_num, clam_step), ~as.vector(scale(.))))

df
```

# Model - Ryan's top models

## m4 and m6

```{r}

#Ryan's m4 - without export
bm4 <- gam(bloom~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               s(Regions, bs='re') +
               season +
               (SAC*season) +
            #replace grazing rate with clam step function
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite,
           family=binomial(link = "logit"),
           data=df)

#Ryan's m6 - with export
bm6 <- gam(bloom~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               EXPORT +
               s(Regions, bs='re') +
               season +
               (SAC*season) +
            #replace grazing rate with clam step function
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite,
            family=binomial(link = "logit"),data=df)


summary(bm4)
summary(bm6)
```

## Adding DissOrthophos m4.po4, m6.po4

```{r}
# Orthophosphos with SAC  (no EXPORT)
bm4.po4 <- gam(bloom ~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               s(Regions, bs='re') +
               season +
               (SAC*season) +
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite+
               DissOrthophos +
               lagDissOrthophos,
             family=binomial(link = "logit"),data=df)

#Orthophosphos with SAC+ EXPORT
bm6.po4 <- gam(bloom ~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               EXPORT +
               s(Regions, bs='re') +
               season +
               (SAC*season) +
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite+
               DissOrthophos +
               lagDissOrthophos,
             family=binomial(link = "logit"),data=df)
summary(bm4.po4)
summary(bm6.po4)
```

# AIC, BIC

## Compare with AIC

```{r}
AIC(bm4,bm6,bm4.po4,bm6.po4)
```

## Compare with BIC

```{r}
BIC(bm4,bm6,bm4.po4,bm6.po4)
```

# Dredging

## GAMs for dredging (drop_na)

```{r, include=FALSE}
df2 <- df %>%
  drop_na()

#Ryan's m4 - without export

bm4d <- gam(bloom~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               s(Regions, bs='re') +
               season +
               (SAC*season) +
            #replace grazing rate with clam step function
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite,
           family=binomial(link = "logit"),
           data=df2)

#Ryan's m6 - with export
bm6d <- gam(bloom~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               EXPORT +
               s(Regions, bs='re') +
               season +
               (SAC*season) +
            #replace grazing rate with clam step function
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite,
            family=binomial(link = "logit"),data=df2)
bm4.po4d <- gam(bloom ~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               s(Regions, bs='re') +
               season +
               (SAC*season) +
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite+
               DissOrthophos +
               lagDissOrthophos,
             family=binomial(link = "logit"),data=df2)

#Orthophosphos with SAC+ EXPORT
bm6.po4d <- gam(bloom ~ DissAmmonia +
               DissNitrateNitrite +
               Temperature +
               Conductivity +
               SAC + 
               EXPORT +
               s(Regions, bs='re') +
               season +
               (SAC*season) +
               clam_step +
               lagSAC +
               lagDissAmmonia +
               lagDissNitrateNitrite+
               DissOrthophos +
               lagDissOrthophos,
             family=binomial(link = "logit"),data=df2)
```

## Dredge top 4 models

```{r dredging, include = FALSE}
options(na.action = "na.fail")

bm4.dredge <- dredge(bm4d)
bm6.dredge <- dredge(bm6d)
bm4.po4.dredge <- dredge(bm4.po4d)
bm6.po4.dredge <- dredge(bm6.po4d)

```

## bm4

```{r}
# bm4.dredge <- dredge(bm4)
head(bm4.dredge)
get.models(bm4.dredge,1)
```

## bm6

```{r}
# bm6.dredge <- dredge(bm6)
head(bm6.dredge)
get.models(bm6.dredge,1)
```

## bm.po4

```{r}
# bm.po4.dredge <- dredge(bm4.po4)
head(bm.po4.dredge)
get.models(bm.po4.dredge,1)
```

## bm.po6

```{r}
# bm.po6.dredge <- dredge(bm4.po6)
head(bm.po6.dredge)
get.models(bm.po6.dredge,1)
```


#shrink top models
