---
title: "HAB toxin analysis"
author: "Schuyler Nardelli"
date: "2026-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prep Workspace
```{r, warning=FALSE, message=FALSE}
# Clear environment, close any open plots
rm(list = ls()); graphics.off()
  
# Load in libraries
library(tidyverse)
library(readxl)
library(EDIutils)
library(dataRetrieval)

# Load BGC PE data
bgc_pe <- read.csv("Data/Cyanotoxins/BGC_PE_2016_2023.csv")

# Load BGC toxin data
bgc_toxin <- read.delim("Data/Cyanotoxins/CyanoWW_2025_cyanotoxins.txt")

# Load PESP data
packageId <-"edi.2209.2"
read_data_package_archive(packageId, path = tempdir()) 
res <- read_data_entity_names(packageId)
entityName <- "PESP_enumeration.csv"
entityId <- res$entityId[res$entityName == entityName]
raw <- read_data_entity(packageId, entityId)
pesp <- readr::read_csv(file = raw)
pesp$Date <- as.Date(pesp$Date)
pesp <- pesp %>% arrange(Date, Time)
rm(res,entityId,entityName,packageId,raw)

# Load EMP toxin data
emp_toxin <- read.csv("Data/Cyanotoxins/San Francisco Estuary cyanoHAB data 2014 to 2019_v1.csv")

# Load Discrete WQ data package (with MVI)
packageId <-"edi.731.7"
read_data_package_archive(packageId, path = tempdir()) 
res <- read_data_entity_names(packageId)

entityName <- "Delta_Integrated_WQ.csv"
entityId <- res$entityId[res$entityName == entityName]
raw <- read_data_entity(packageId, entityId)
wq <- readr::read_csv(file = raw)
rm(entityId,entityName,raw)

entityName <- "Delta_Integrated_WQ_metadata.csv"
entityId <- res$entityId[res$entityName == entityName]
raw <- read_data_entity(packageId, entityId)
wq_meta <- readr::read_csv(file = raw)
rm(res,entityId,entityName,packageId,raw)

wq$Date <- as.Date(wq$Date)
wq <- wq %>% separate(Station, into = c("Survey", "Station"), sep = " ")
wq <- wq[, -c(2,4:5)]
wq <- wq[,c("Source","Station","Date","Datetime","Sample_depth_surface","Tide",
           "Temperature","Conductivity","Salinity","Secchi","TurbidityNTU","TurbidityFNU",
           "DissolvedOxygen","DissolvedOxygenPercent","pH","Microcystis","Chlorophyll","Pheophytin",
           "TotAmmonia","DissAmmonia","DissNitrateNitrite","TotPhos","DissOrthophos","TON","DON",
           "TKN","TotAlkalinity","DissBromide","DissCalcium","TotChloride","DissChloride","DissSilica",
           "TOC","DOC","TDS","TSS","VSS")]



```

## Merge BGC data
```{r, warning=FALSE, message=FALSE}

bt <- bgc_toxin %>% 
  filter(Toxin.Class %in% c("Microcystins","Nodularin","Microcystins and Nodularin") & is.na(REP.ID)) %>%
  rename(BGC_ID=BGC.ID,Datetime=Timestamp..PST..DS,Station=Station.Abbrev..DS,Concentration=Result.Value..ug.L.) %>%
  group_by(BGC_ID,Datetime,Station) %>%
  summarize(Concentration = sum(Concentration))

bp <- bgc_pe %>%
  filter(division == "cyanobacteria") %>%
  rename(BGC_ID=bgc_id,Density=cells_per_ml,Biovolume=biovolume_um3_per_ml) %>%
  group_by(BGC_ID) %>%
  summarize(Density=sum(Density),Biovolume=sum(Biovolume))

tot <- bgc_pe %>% rename(BGC_ID=bgc_id) %>% group_by(BGC_ID) %>% summarise(Tot_Density = sum(cells_per_ml),Tot_Biovolume = sum(biovolume_um3_per_ml))
bp <- bp %>% left_join(tot,by=c("BGC_ID"))
bp$Rel_Biovolume <- (bp$Biovolume/bp$Tot_Biovolume)*100;
bp$Rel_Density <- (bp$Density/bp$Tot_Density)*100;
rm(tot)

bgc <- merge(bt, bp, by = "BGC_ID", all.x = TRUE)
bgc$Date <- as.Date(bgc$Datetime, format = "%m/%d/%Y %H:%M")

bgc2 <- left_join(bgc,wq,by = c("Date","Station")) # Need better Chl and MVI data

```


## Merge EMP data
```{r, warning=FALSE, message=FALSE}

et <- emp_toxin %>% 
  filter(Toxin.Class %in% c("Microcystins","Nodularin","Microcystins and Nodularin") & is.na(REP.ID)) %>%
  rename(BGC_ID=BGC.ID,Datetime=Timestamp..PST..DS,Station=Station.Abbrev..DS,Concentration=Result.Value..ug.L.) %>%
  group_by(BGC_ID,Datetime,Station) %>%
  summarize(Concentration = sum(Concentration))

ep <- bgc_pe %>%
  filter(division == "cyanobacteria") %>%
  rename(BGC_ID=bgc_id,Density=cells_per_ml,Biovolume=biovolume_um3_per_ml) %>%
  group_by(BGC_ID) %>%
  summarize(Density=sum(Density),Biovolume=sum(Biovolume))

tot <- bgc_pe %>% rename(BGC_ID=bgc_id) %>% group_by(BGC_ID) %>% summarise(Tot_Density = sum(cells_per_ml),Tot_Biovolume = sum(biovolume_um3_per_ml))
bp <- bp %>% left_join(tot,by=c("BGC_ID"))
bp$Rel_Biovolume <- (bp$Biovolume/bp$Tot_Biovolume)*100;
bp$Rel_Density <- (bp$Density/bp$Tot_Density)*100;
rm(tot)

bgc <- merge(bt, bp, by = "BGC_ID", all.x = TRUE)
bgc$Date <- as.Date(bgc$Datetime, format = "%m/%d/%Y %H:%M")

bgc2 <- left_join(bgc,wq,by = c("Date","Station")) # Need better Chl and MVI data

```


## Plot BGC toxin vs. rel abundance
```{r, warning=FALSE, message=FALSE}

ggplot(data=bgc) +
  geom_point(aes(x=Rel_Biovolume,y=Concentration))

```

