---
title: "Seasonal Analysis"
author: "Alex Berk"
date: "2025-08-21"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Read in packages
```{r Read in Packages, include=FALSE}
library(tidyverse)
library(mgcv)
library(MuMIn)
library(gratia)
library(sf)
library(plotly)
theme_set(theme_classic())
```


Read in Water quality data
```{r Read in Alexs csv, include=FALSE}
# #read in Alex CSV
# wq <- read.csv("Data/edi_df_integrate_monthly.csv") %>%
#   filter(ymd(year_month) >= ymd(19790101))
# 
# #Ryan clams file 
# cl <- read.csv("data/combined_clams_dataset.csv")

#Read in Ryan CSV
wq_r_sum <- read_csv("Data/regional_integrated_dataset2.csv") %>%
  select(-TotAmmonia) %>%
  select(Regions, season, seasonyear,year_month,Chlorophyll,Clam_biomass:Clam_filtration,DissAmmonia:lagOUT_max_var_sm)
```

Restructure to long for facet wrap
```{r Attach Regions and Clean up Data, include=FALSE}

wq_longsn <- wq_r_sum %>%
  pivot_longer(cols=Clam_biomass:lagOUT_max_var_sm,names_to="Covariate_name",values_to="Covariate_value") %>%
  mutate(logvalue = log(Covariate_value)) %>%
  filter(!is.infinite(logvalue)&
         !is.nan(logvalue))
```


Create some histograms
```{r}
histchl <- wq_longsn %>%
  ggplot(aes(x=Chlorophyll))+
  geom_histogram()+
  ggtitle("Chlorophyll Histogram Full Delta")
histchl

histchlsd <- wq_longsn %>%
  filter(Regions %in% "South") %>%
  ggplot(aes(x=Chlorophyll))+
  geom_density() + 
  ggtitle("Density curve South Delta")
histchlsd

histcovt <- wq_longsn %>%
  filter(Covariate_name %in% c("Temperature","lagTemperature")) %>%
  ggplot(aes(x=Covariate_value)) +
  geom_histogram(binwidth = 2) + 
  facet_wrap(~Covariate_name, ncol = 4, scales = "free")+
  theme_bw()+
  ggtitle("Temp Histograms")
histcovt
  
```

Explore Relationships Among Discrete Chlorophyll A and Other Predictor Variables with seasonal lag
```{r Explore Relationships Among Discrete Chlorophyll A and Other Predictor Variables}

plot <- wq_longsn %>% 
  filter(!grepl("OUT",Covariate_name) & !grepl("SAC",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 4, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - seasonal lag - WQ")
plot
# p1 <- ggplotly(plot)
# htmlwidgets::saveWidget(as_widget(p1), "figures/delta_wide.html")

plot2 <- wq_longsn %>% 
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           !grepl("var",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 4, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - seasonal lag - flow")
plot2

plot3 <- wq_longsn %>% 
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           grepl("var",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 4, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - seasonal lag - flow variance")
plot3

#ggplotly(plot2)

# p2 <- ggplotly(plot2)
# htmlwidgets::saveWidget(as_widget(p2), "figures/delta_wide_flow.html")

```


Explore Relationships Among Discrete Chlorophyll A and Other Predictor Variables by Season
```{r Explore Relationships Among Discrete Chlorophyll A and Other Predictor Variables by Season - Spring}

#SUMMER
#Water Quality
plot_spring <- wq_longsn %>%
  filter(season %in% "Spring") %>%
  filter(!grepl("OUT",Covariate_name) & !grepl("SAC",Covariate_name) & !grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 4, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - WQ - spring")
plot_spring
# p1 <- ggplotly(plot)
# htmlwidgets::saveWidget(as_widget(p1), "figures/delta_wide.html")

#Water Quality with Lags
plot_spring2 <- wq_longsn %>%
  filter(season %in% "Spring") %>%
  filter(!grepl("OUT",Covariate_name) & !grepl("SAC",Covariate_name) & grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - WQ - spring - seasonal lag")
plot_spring2

#flows - maxes and averages
plot_spring3 <- wq_longsn %>% 
  filter(season %in% "Spring") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           !grepl("var",Covariate_name) &
           !grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow - spring")
plot_spring3

#flows - maxes and averages
plot_spring4 <- wq_longsn %>% 
  filter(season %in% "Spring") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           !grepl("var",Covariate_name) &
           grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow - spring - seasonal lag")
plot_spring4

plot_spring5 <- wq_longsn %>%
  filter(season %in% "Spring") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           grepl("var",Covariate_name) &
           !grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow variance - spring")
plot_spring5

plot_spring6 <- wq_longsn %>%
  filter(season %in% "Spring") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           grepl("var",Covariate_name) &
           grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow variance - spring - seasonal lag")
plot_spring6


```

```{r Explore Relationships Among Discrete Chlorophyll A and Other Predictor Variables by Season - Summer}
#SUMMER
#Water Quality
plot_Summer <- wq_longsn %>%
  filter(season %in% "Summer") %>%
  filter(!grepl("OUT",Covariate_name) & !grepl("SAC",Covariate_name) & !grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 4, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - WQ - Summer")
plot_Summer
# p1 <- ggplotly(plot)
# htmlwidgets::saveWidget(as_widget(p1), "figures/delta_wide.html")

#Water Quality with Lags
plot_Summer2 <- wq_longsn %>%
  filter(season %in% "Summer") %>%
  filter(!grepl("OUT",Covariate_name) & !grepl("SAC",Covariate_name) & grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - WQ - Summer - seasonal lag")
plot_Summer2

#flows - maxes and averages
plot_Summer3 <- wq_longsn %>% 
  filter(season %in% "Summer") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           !grepl("var",Covariate_name) &
           !grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow - Summer")
plot_Summer3

#flows - maxes and averages
plot_Summer4 <- wq_longsn %>% 
  filter(season %in% "Summer") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           !grepl("var",Covariate_name) &
           grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow - Summer - seasonal lag")
plot_Summer4

plot_Summer5 <- wq_longsn %>%
  filter(season %in% "Summer") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           grepl("var",Covariate_name) &
           !grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow variance - Summer")
plot_Summer5

plot_Summer6 <- wq_longsn %>%
  filter(season %in% "Summer") %>%
  filter((grepl("OUT",Covariate_name) | grepl("SAC",Covariate_name)) &
           grepl("var",Covariate_name) &
           grepl("lag",Covariate_name)) %>% 
  ggplot(aes(x=Covariate_value, y=(Chlorophyll),color=Regions))+
    geom_point()+
    facet_wrap(~Covariate_name, ncol = 3, scales = "free")+
    theme_bw()+
    ggtitle("Delta wide - flow variance - Summer - seasonal lag")
plot_Summer6
```


